# Generated by Django 2.1.7 on 2019-03-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Informe a marca do produto', max_length=300, verbose_name='Marca do produto')),
                ('nome', models.CharField(help_text='Informe o nome do produto', max_length=150, verbose_name='Nome do produto')),
                ('sabor', models.CharField(help_text='Informe o sabor do produto', max_length=150, verbose_name='Sabor do produto')),
                ('preco', models.CharField(help_text='Digite o preço do produto', max_length=50, verbose_name='Preço do produto')),
                ('quantidade', models.CharField(help_text='Informe a quantidade desejada de produtos', max_length=100, verbose_name='Quantidade desejada')),
            ],
        ),
    ]
