# Generated by Django 2.1.7 on 2019-03-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_estoque_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='categoria',
            field=models.CharField(default='', help_text='Informe a categoria do produto', max_length=150, verbose_name='Categoria do produto'),
        ),
    ]
